### ISSUE TITLE
Improvement suggestion: merge meeting-crawler.edn with config.edn

### ISSUE THREAD

**Issue by pmonks** [finos/metadata-tool#52]
When a developer is trying to understand how a codebase configures itself, one of the biggest root causes of [accidental complexity](https://en.wikipedia.org/wiki/No_Silver_Bullet) is having multiple configuration mechanisms, formats, and/or locations.  With the introduction of the `meeting-crawler.edn` file, the `metadata-tool` now suffers from this problem.

Originally, the `metadata-tool` was intentionally designed to have a single, clearly documented configuration file ([`config.edn`](https://github.com/finos/metadata-tool#configuration)) for *all* configuration, specifically to avoid this issue. 
 This was based, in part, upon prior experience of large Spring-based applications which tend to end up with hundreds (or more!) of small, isolated XML and Java properties files, making it practically impossible to statically determine (i.e. solely from the code) how a particular runtime instance of the application is actually configured.

**Comment by maoo** [comment]
Hi @pmonks , thanks for the suggestion.

We actually deprecated the whole code and decided to implement meeting attendance tracking on GitHub Issues, see https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Project+Collaboration+on+Github#ProjectCollaborationonGithub-MeetingMinutes . I also made `meeting-crawler.edn` optional, so that the main function doesn't complain if it's missing.

I'm closing the issue as `wont fix`, code is already updated on master branch.

TY for the suggestion!
